var paises = [
    "Afeganistão",
    "África do Sul",
    "Albânia",
    "Alemanha",
    "Andorra",
    "Angola",
    "Antígua e Barbuda",
    "Arábia Saudita",
    "Argélia",
    "Argentina",
    "Arménia",
    "Austrália",
    "Áustria",
    "Azerbaijão",
    "Bahamas",
    "Bangladexe",
    "Barbados",
    "Barém",
    "Bélgica",
    "Belize",
    "Benim",
    "Bielorrússia",
    "Bolívia",
    "Bósnia e Herzegovina",
    "Botsuana",
    "Brasil",
    "Brunei",
    "Bulgária",
    "Burquina Faso",
    "Burundi",
    "Butão",
    "Cabo Verde",
    "Camarões",
    "Camboja",
    "Canadá",
    "Catar",
    "Cazaquistão",
    "Chade",
    "Chile",
    "China",
    "Chipre",
    "Colômbia",
    "Comores",
    "Congo-Brazzaville",
    "Congo-Kinshasa",
    "Coreia do Norte",
    "Coreia do Sul",
    "Cosovo",
    "Costa do Marfim",
    "Costa Rica",
    "Croácia",
    "Cuaite",
    "Cuba",
    "Dinamarca",
    "Dominica",
    "Egito",
    "Emirados Árabes Unidos",
    "Equador",
    "Eritreia",
    "Eslováquia",
    "Eslovénia",
    "Espanha",
    "Estados Unidos",
    "Estónia",
    "Etiópia",
    "Fiji",
    "Filipinas",
    "Finlândia",
    "França",
    "Gabão",
    "Gâmbia",
    "Gana",
    "Geórgia",
    "Granada",
    "Grécia",
    "Guatemala",
    "Guiana",
    "Guiné",
    "Guiné Equatorial",
    "Guiné-Bissau",
    "Haiti",
    "Honduras",
    "Hungria",
    "Iémen",
    "Ilhas Marechal",
    "Índia",
    "Indonésia",
    "Irão",
    "Iraque",
    "Irlanda",
    "Islândia",
    "Israel",
    "Itália",
    "Jamaica",
    "Japão",
    "Jibuti",
    "Jordânia",
    "Laus",
    "Lesoto",
    "Letónia",
    "Líbano",
    "Libéria",
    "Líbia",
    "Listenstaine",
    "Lituânia",
    "Luxemburgo",
    "Macedónia do Norte",
    "Madagáscar",
    "Malásia",
    "Maláui",
    "Maldivas",
    "Mali",
    "Malta",
    "Marrocos",
    "Maurícia",
    "Mauritânia",
    "México",
    "Micronésia",
    "Moçambique",    
    "Moldávia",    
    "Mônaco",    
    "Mongólia",    
    "Montenegro",    
    "Marrocos",    
    "Mianmar",    
    "Namíbia",    
    "Nauru",    
    "Nepal",    
    "Nicarágua",    
    "Níger",    
    "Nigéria",    
    "Noruega",    
    "Nova Zelândia",    
    "Omã",    
    "Países Baixos",    
    "Palau",    
    "Panamá",    
    "Papua Nova Guiné",   
    "Paquistão",    
    "Paraguai",    
    "Peru",    
    "Polônia",    
    "Portugal",    
    "Quênia",    
    "Quirguistão",    
    "Reino Unido",    
    "República Centro-Africana",    
    "República Dominicana",    
    "República Tcheca",    
    "Romênia",    
    "Ruanda",    
    "Rússia",    
    "Ilhas Salomão",    
    "Salvador",    
    "Samoa",    
    "Santa Lúcia",    
    "São Cristóvão e Nevis",    
    "São Marinho",    
    "São Tomé e Príncipe",    
    "São Vicente e Granadinas",    
    "Senegal",    
    "Serra Leoa",    
    "Sérvia",    
    "Síria",    
    "Somália",   
    "Sri Lanka",    
    "Suazilândia",    
    "Sudão",    
    "Sudão do Sul",    
    "Suécia",    
    "Suíça",    
    "Suriname",    
    "Tadjiquistão",    
    "Tailândia",    
    "Tanzânia",    
    "Timor-Leste",    
    "Togo",    
    "Tonga",    
    "Trinidad e Tobago",    
    "Tunísia",    
    "Turcomenistão",    
    "Turquia",    
    "Tuvalu",    
    "Ucrânia",    
    "Uganda",    
    "Uruguai",    
    "Uzbequistão",    
    "Vanuatu",    
    "Vaticano",    
    "Venezuela",    
    "Vietnã",    
    "Zâmbia",    
    "Zimbábue"
]; 
  
function gerarPais() {
    var index = Math.floor(Math.random() * paises.length);
    document.getElementById("pais").value = paises[index];
}
